fix: исправил уязвимость в API для GameController
16Shadows/BardsAndDragons pull request #32
Opened 2024-05-26 13:21 UTC by GlarkDen

- теперь конфиденциальные данные не передаются на клиента
- не авторизованный клиент не имеет доступа к API с данными пользователя
- добавлена базовая обработка ошибок
- весь функционал для работы с играми перенесён в GameController
- добавлена обработка ошибок
- добавлены оптимизации useMemo, useCallback

2024-06-22 21:15 UTC, GlarkDen commented on client/src/components/ModalWindowAlert/ModalWindowAlert.tsx
> +const ModalWindowAlert = ({show = false, onHide, message = "Сообщение"}: IProps) => {
В компоненте `ModalWindowAlert` вынес `children`. В компоненте с ошибкой оставил сообщение, потому что в нём это именно сообщение.

2024-06-22 21:15 UTC, GlarkDen commented on client/src/components/ModalWindowAlert/ModalWindowAlert.tsx
> +            <Modal.Title style={{ color: "red" }}>{"Произошла ошибка"}</Modal.Title>
Сделал два компонента `ModalWindowAlert` и наследующий его `ModalWindowAlertError`

2024-06-22 21:15 UTC, GlarkDen commented on client/src/components/ModalWindowAlert/ModalWindowAlert.tsx
> +            </p>
Сделал два компонента `ModalWindowAlert` и наследующий его `ModalWindowAlertError`

2024-06-22 21:15 UTC, GlarkDen commented on src/controllers/GameController.ts
> +        // Задержка для тестирования
Вроде в беседе обсуждали, могу оставить на беке? Или вырезать?

2024-06-23 07:30 UTC, 16Shadows commented on src/controllers/GameController.ts
> +
К текущему, речь о литеральной константе "id".

2024-06-23 07:30 UTC, 16Shadows commented on src/controllers/GameController.ts
> +
К текущему, речь о литеральной константе "id".

2024-06-23 07:34 UTC, GlarkDen commented on client/src/pages/SearchGamesPage/SearchGamesPage.tsx
> +            totalGamesNumber.current = response.data;
Сделал версионирование запросов

2024-06-23 07:34 UTC, GlarkDen commented on client/src/pages/SearchGamesPage/SearchGamesPage.tsx
> +                }, 750);
Вынес обработку этого условия в getGames с версионированием

2024-06-23 07:34 UTC, GlarkDen commented on client/src/pages/SearchGamesPage/SearchGamesPage.tsx
> +                            <input style={{ width: "100%" }} value={searchQuery} onChange={e => setSearchQuery(e.target.value)} />
Сделано

2024-06-23 07:34 UTC, GlarkDen commented on src/controllers/GameController.ts
> +
Но её там нету

2024-06-23 10:29 UTC, 16Shadows requested changes

2024-06-23 10:29 UTC, 16Shadows commented on client/src/pages/SearchGamesPage/SearchGamesPage.tsx
> +    async function subscribe(gameId: number): Promise<boolean | undefined> {
useCallback

2024-06-23 10:29 UTC, 16Shadows commented on client/src/pages/SearchGamesPage/SearchGamesPage.tsx
> +    async function unsubscribe(gameId: number): Promise<boolean | undefined> {
useCallback

2024-06-23 10:36 UTC, GlarkDen commented on client/src/pages/SearchGamesPage/SearchGamesPage.tsx
> +    function unsubscribe(gameId: number) {
Сделано

2024-06-23 10:36 UTC, GlarkDen commented on client/src/pages/SearchGamesPage/SearchGamesPage.tsx
> +    function subscribe(gameId: number) {
Сделано

2024-06-23 10:36 UTC, GlarkDen commented on client/src/pages/SearchGamesPage/SearchGamesPage.tsx
> +    async function subscribe(gameId: number): Promise<boolean | undefined> {
Сделано

2024-06-23 10:36 UTC, GlarkDen commented on client/src/pages/SearchGamesPage/SearchGamesPage.tsx
> +    async function unsubscribe(gameId: number): Promise<boolean | undefined> {
Сделано

2024-06-23 10:39 UTC, 16Shadows requested changes

2024-06-23 10:39 UTC, 16Shadows commented on client/src/components/GameItem/GameItem.tsx
> +                        <button className="game-button" onClick={() => navigate(`/game/${game.id}`)}>{game.name}</button>
Заменить строковой литерал в пути на вызов функции для генерации пути.

2024-06-23 14:27 UTC, GlarkDen commented on client/src/components/GameItem/GameItem.tsx
> +                        <button className="game-button" onClick={() => navigate(`/game/${game.id}`)}>{game.name}</button>
Сделано

2024-06-23 14:47 UTC, 16Shadows approved these changes

2024-06-23 15:07 UTC, merged