Feat: страница моих игр
16Shadows/BardsAndDragons pull request #45
Opened 2024-06-18 19:08 UTC by NickP59

2024-06-19 07:26 UTC, 16Shadows commented
Добавить описание, починить конфликты

2024-06-19 07:47 UTC, 16Shadows requested changes

2024-06-19 07:47 UTC, 16Shadows commented on client/src/pages/MyGamesPage/MyGamesPage.tsx
> +            <Tab title='Мои игры' eventKey='game-list' className="p-2">
А зачем во вкладки обёрнут список игр?

2024-06-19 07:47 UTC, 16Shadows commented on src/controllers/UserGameController.ts
> +import { AuthMiddleware, AuthMiddlewareBag } from "../middleware/AuthMiddleware";
Согласовать название файла с названием содержащегося класса.

2024-06-19 07:47 UTC, 16Shadows commented on src/controllers/UserGameController.ts
> +    async addGame(bag: AuthMiddlewareBag, userGame: Game) {
Метод есть в https://github.com/16Shadows/BardsAndDragons/pull/46/files, согласовать название, путь и реализацию.

2024-06-19 07:47 UTC, 16Shadows commented on src/controllers/UserGameController.ts
> +    async removeGame(bag: AuthMiddlewareBag, userGame: Game) {
Метод есть в https://github.com/16Shadows/BardsAndDragons/pull/46/files, согласовать название, путь и реализацию.

2024-06-19 07:59 UTC, 16Shadows requested changes

2024-06-19 07:59 UTC, 16Shadows commented on src/controllers/UserGameController.ts
> +            .addSelect('COALESCE(game.name)', 'name')
Зачем COALESCE из одного аргумента?

2024-06-19 13:28 UTC, NickP59 commented on client/src/pages/MyGamesPage/MyGamesPage.tsx
> +            <Tab title='Мои игры' eventKey='game-list' className="p-2">
только ради надписи на вкладке и единого стиля. Может под расширение какое-нибудь в будущем. А так могу убрать, добавить надпись

2024-06-19 13:40 UTC, NickP59 commented on src/controllers/UserGameController.ts
> +            .addSelect('COALESCE(game.name)', 'name')
без него не работает

2024-06-19 15:22 UTC, 16Shadows commented on src/controllers/UserGameController.ts
> +            .addSelect('COALESCE(game.name)', 'name')
Не работает, потому что без этой строки в запросе отсутствует поле name. Строку можно заменить на `.addSelect('game.name', 'name')`

2024-06-22 10:42 UTC, 16Shadows requested changes

2024-06-22 10:42 UTC, 16Shadows commented on client/src/pages/MyGamesPage/GameItem.css
> +    text-overflow: ellipsis;
Здесь лучше не `text-overflow` использовать, а `word-break: break-all`, чтобы текст переносился при переполнении в любом месте (в том числе посреди слова), а не терялся.

2024-06-22 11:28 UTC, 16Shadows approved these changes

2024-06-22 11:31 UTC, merged